### ISSUE TITLE
Print recipe errors

### ISSUE THREAD

**Issue by schuessm** [Gremmel/kleiner-brauhelfer#11]
When I brint the recipe following errors occur:

- the weight of hope is wrong
- the time for the hope given is wrong, e.g. in the recipe i define 10 min before end of cooking and on the recipe printout i read after 10 min.

**Comment by bitwave** [comment]
Do you have an example xsud file?

**Comment by LondonRain** [comment]
When this is not reproducible I suggest it should be closed. The timing issue might just be a misinterpretation of minutes in the boil or to the end of boil.

**Comment by schuessm** [comment]
Sorry, I just read it, it was a misinterpretation. I unterstood the values now :-)
