### ISSUE TITLE
path of DB with linux can't be changed

### ISSUE THREAD

**Issue by schuessm** [Gremmel/kleiner-brauhelfer#12]
I have an issue with changing the database storage place for example on my NAS, I need it bwcause I want read the DB from difference computers. With Windows a network path is working but not with linux.

**Comment by freibadschwimmer** [comment]
I'm not sure if I can properly respond to your issue, but I also use one database on different computers:

My solution is, that I have the database somewhere in my regular documents folder, and sync it to my owncloud instance, from where the file is in sync with my other machines. Maybe you could use this as a workaround in case you can't find a proper answer to your question.

**Comment by schuessm** [comment]
That is what I do actual. But i must copy always the DB from my Cloud/Nas to my local computer

**Comment by BourgeoisLab** [comment]
Is this still an issue? Please be more specific.
