### ISSUE TITLE
The ordinal 4369 could not be located in the dynamic library Libeay32.dll

### ISSUE THREAD

**Issue by johanmk** [Gremmel/kleiner-brauhelfer#13]
Hello. I get this error message when I open the application.
And it is not possible to get the English language.
![capture1](https://cloud.githubusercontent.com/assets/17314054/24500908/aadd5dfc-1547-11e7-9246-110451c8a4a4.GIF)

**Comment by BourgeoisLab** [comment]
Libeay32.dll is a dll for SSL support. Check your Qt installation.
Englisch is now supported.
