### ISSUE TITLE
Importing from xsud does not import amount of additional ingredients

### ISSUE THREAD

**Issue by LondonRain** [Gremmel/kleiner-brauhelfer#16]
When importing from an xsud file that has additional ingredients (like 5g/l dry hopping) it does not import the amount. It's always replaced by 0. Might be an issue with decimal separators? Comma vs. point...

**Comment by BourgeoisLab** [comment]
Thanks for reporting. Bug is fixed.

You can try it manually be changing the lines:
`<AMOUNT Einheit="Gramm/Liter">...</AMOUNT>`
to 
`<Menge Einheit="Gramm/Liter">...</Menge>`
in the .xsud file.
