### ISSUE TITLE
Calculate mash in temperature

### ISSUE THREAD

**Issue by LondonRain** [Gremmel/kleiner-brauhelfer#19]
It would be nice if there would be a small "..." button next to the mash in temperature box. It should open a small popup window where one could enter the grain (and perhaps the boil) temperature. Given the known malt weight and first rest temperature it could calculate and fill in the mash in temperature.

Usually I do this manually using this site:
https://www.brewersfriend.com/mash/
--> Switch to "Metric" and "Strike Water volume"

**Comment by BourgeoisLab** [comment]
Done. Expect this feature in the new version I want to release this week.
Cheers

**Comment by LondonRain** [comment]
Cool, thanks a lot! Looking forward to it. It will round the decimal temperature up or down when necessary?
