### ISSUE TITLE
Potential logic error in mainwindowimpl.cpp?

### ISSUE THREAD

**Issue by m-schmidt** [Gremmel/kleiner-brauhelfer#23]
When compiling with clang on macOS there is a warning in `src/mainwindowimpl.cpp`:

    src/mainwindowimpl.cpp:4553:9: warning: logical not is only applied to the left hand side of this comparison
          [-Wlogical-not-parentheses]
        if (!list_EwZutat[i]->getZeitpunkt() == EWZ_Zeitpunkt_Gaerung) {
            ^                                ~~

Does this code really intend to do `if ((!a) == b)` or should id rather be `if (a != b)`? One should add explicit parentheses to silence the warning.

**Comment by BourgeoisLab** [comment]
This is wrong. It should be "!=". Thanks for the report.
Sad that windows and linux compiler don't report this possible error.
