### ISSUE TITLE
do not color expiry date if inventory is empty

### ISSUE THREAD

**Issue by realholgi** [Gremmel/kleiner-brauhelfer#25]
In version 1.4.4.1 there is the new feature of coloring expired malts, hops, yeasts, ...

I recommend not coloring the expiry date if the inventory of the malts, hops, yeasts, ... is empty.

**Comment by realholgi** [comment]
Example Screenshot ![shot](https://user-images.githubusercontent.com/980419/34649508-f23e311a-f3b0-11e7-981b-5c87572a6af5.png)

**Comment by BourgeoisLab** [comment]
Done. In the next version both date input fields will be disabled and not red if the ingredient is empty.

**Comment by realholgi** [comment]
Cool, works great!

![shot2](https://user-images.githubusercontent.com/980419/34654115-2992e70a-f3f7-11e7-91be-9314cdf86236.png)
