### ISSUE TITLE
Cell colors are lost when not focused

### ISSUE THREAD

**Issue by LondonRain** [Gremmel/kleiner-brauhelfer#31]
The colors from highlighting cells in the ingredients tab are lost when the application loses its focus.

Is focused:
![grafik](https://user-images.githubusercontent.com/33151586/34845359-ea04c2c2-f714-11e7-86e9-57ba8cd3508b.png)

Another window is focused:
![grafik](https://user-images.githubusercontent.com/33151586/34845399-0542b756-f715-11e7-8ee2-99afbbcc8d97.png)

Windows 7, 1.4.4.1

**Comment by BourgeoisLab** [comment]
fixed
