### ISSUE TITLE
Ctrl-Q to quit. Turn off confirmation.

### ISSUE THREAD

**Issue by ivh** [Gremmel/kleiner-brauhelfer#32]
Ctrl-Q does not work for me to quit, running on Debian/Squeeze with Gnome.

Also, I think the confirmation dialogue to quit is new, and I would rather not have it. (Unless there are unsaved changes, of course, as before)

cheers & thanks!
/thomas

**Comment by BourgeoisLab** [comment]
Ctrl-Q to quit is now implemented.

**Comment by ivh** [comment]
I see the option to turn off the quit-conformation is done as well! Vielen Dank!
