### ISSUE TITLE
Path of DB not changeable (Linux)

### ISSUE THREAD

**Issue by schuessm** [Gremmel/kleiner-brauhelfer#33]
Hello,

I work with Linux Ubuntu 16.04, and I can't change the path of the database. When I change it KB doesn't start again. Thats a problem because I develope the recipe on my Desktop-PC and then on a brewing day I use a old notebook.

**Comment by BourgeoisLab** [comment]
More information needed.
Make sure the path is readable and writeable.

**Comment by schuessm** [comment]
Yes the path is read and writeable. I push the DB to my NAS in an existing folder which I use on the same Computer for e.g. Documents and I've access to this folder and there documents. The issue exists since the old version.

**Comment by BourgeoisLab** [comment]
Still can't reproduce. Do you have any success?

**Comment by schuessm** [comment]
I solve it use a USB-Stick or copy it from Nas to lokal PC
