### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by LondonRain** [Gremmel/kleiner-brauhelfer#34]
I am not good with commas too, but there should probably be some.

![grafik](https://user-images.githubusercontent.com/33151586/34910597-e625fc5c-f8b8-11e7-8093-47ef48dccd98.png)

Perhaps:
"Zutaten, die bei der Gärung hinzugegeben werden, werden jetzt nicht verrechnet."

**Comment by BourgeoisLab** [comment]
fixed.
