### ISSUE TITLE
printing the Spickzettel

### ISSUE THREAD

**Issue by henneonrails** [Gremmel/kleiner-brauhelfer#36]
doesen't work in 1.4.4.1 on a mac. Save to file and print with preview does work fine.

**Comment by realholgi** [comment]
There will be no direct print command in the next version anymore. See https://github.com/Gremmel/kleiner-brauhelfer/commit/f53a71ff708e57fc5362fbd488ae3073bd96fd5b

**Comment by henneonrails** [comment]
ok thank you
