### ISSUE TITLE
Create PKGBUILD for Arch Linux

### ISSUE THREAD

**Issue by bitwave** [Gremmel/kleiner-brauhelfer#38]
At https://aur.archlinux.org/packages/kleiner-brauhelfer/ is an old version, of the brauhelfer, but since the language update the PKGBUILD does not work anymore. Maybe it is possible to write one and keep it updated in this repository like the debian version.

**Comment by BourgeoisLab** [comment]
If someone is willing to invest some time in keeping the linux version up to date, feel free to contact me or gremmel.
