### ISSUE TITLE
Columns in Overview

### ISSUE THREAD

**Issue by ivh** [Gremmel/kleiner-brauhelfer#40]
I'm missing a column for the yeast in the "Brau-Übersicht"-tab.

Ideally, columns for this vew could be (de-)selectable from the settings?

cheers & thanks!
/thomas

**Comment by BourgeoisLab** [comment]
First I wanted to add a yeast column. But there are plans to allow multiple yeasts in the future. So this would be a bit messy to represent.

Selecting columns would be indeed nice. But not a priority issue.

**Comment by ivh** [comment]
Yes, the selectable comumns is certainly a "wish list"-item.

If you want to add a yeast-columun anyway, simply appending the names of all yeasts would be a simple solution, once there are several per batch.

**Comment by BourgeoisLab** [comment]
Done
