### ISSUE TITLE
Create a debian package with 1.4.5

### ISSUE THREAD

**Issue by schuessm** [Gremmel/kleiner-brauhelfer#42]
When I use QCreator with QT 5.10 and compile the source I get the following messages:

```
/usr/lib/x86_64-linux-gnu/libGL.so : -1 : Fehler: Nicht definierter Verweis auf `drmGetDevices2'
/usr/lib/x86_64-linux-gnu/libGL.so : -1 : Fehler: Nicht definierter Verweis auf `drmGetDevice2'
: -1 : Fehler: collect2: error: ld returned 1 exit status
```

Can you help me, perhaps an howto what are the settings for compiling.

Thank you!

**Comment by BourgeoisLab** [comment]
This is a linker error. Try to update/reinstall the GL library (libgl1-mesa-dev)
from [http://doc.qt.io/qt-5/linux.html](url):
`sudo apt update`
`sudo apt-get install build-essential libgl1-mesa-dev`

**Comment by schuessm** [comment]
Thank you for your help. The problem persist. Do you have any other idea?

**Comment by schuessm** [comment]
I works now on a VM machine with ubuntu 17.10, it didn't works on my ubuntu 16.04, I don't know why. But so what. Now ist my question how can I generate the deb-File. With QT-Creator I can run it, but I don'tknow how can I compile the project to a DEB

**Comment by schuessm** [comment]
Wow, After days of searching I found my solution:
https://support.amd.com/en-us/kb-articles/Pages/AMDGPU-PRO-Install.aspx
The problem came with an Ubuntu update
