### ISSUE TITLE
Missing brews in "Brau-Übersicht"

### ISSUE THREAD

**Issue by LondonRain** [Gremmel/kleiner-brauhelfer#44]
Somehow a brew does not appear directly in the "Brau-Übrsicht" directly after having marked it as brewed or filled. It always takes some weeks. I assume it has something to do with the "Reifezeit" which probably is added on one of the dates and only after that time it appears in the grid in the "Brau-Übersicht". However I do not see a point in that. It should be included in the list once it's marked as brewed.

**Comment by realholgi** [comment]
Maybe you have acivated a filtered view (the radio buttons above the "Brau-Übrsicht") and not selected "Show all"?

**Comment by BourgeoisLab** [comment]
I think he means "Brau-Übersicht" and not the first tab "Sudauswahl". Anyway the brew should appear directly after set the "bottled". Check the dates below the table.

**Comment by LondonRain** [comment]
Ah... my fault. I entered the bottled date and saved it, but I did not mark it as bottled. Thanks a lot!

Tim

**Comment by LondonRain** [comment]
However... Can't it be added to the overview directly after having it marked as brewed? Values that will be determined only when already bottled could be leaved blank.
