### ISSUE TITLE
Wrong molecular weight for Calcium?

### ISSUE THREAD

**Issue by m-schmidt** [Gremmel/kleiner-brauhelfer#46]
In file `mainwindowimpl.cpp` line `9512`:

    void MainWindowImpl::on_SpinBox_wwCalcium_mg_valueChanged(double) {
      if (SpinBox_wwCalcium_mg->hasFocus()) {
        // umrechnen in mmol
        double d;
        d = SpinBox_wwCalcium_mg->value();
        d = d / 40.8;
        [...]

According to Wikipedia and MMuM, the molecular weight of Calcium is about `40.08`, not `40.8`. The same wrong constant is also used in `on_SpinBox_wwCalcium_mmol_valueChanged()` and `BerWasserwerte()` of the same file. I cannot find other occurrences of `40.8` except these three.

Note: I'm not 100% sure. Please review carefully, but the impact should be minimal.

**Comment by BourgeoisLab** [comment]
nice one! fixed
