### ISSUE TITLE
Knopf zum Zumischen verschwunden

### ISSUE THREAD

**Issue by ivh** [Gremmel/kleiner-brauhelfer#50]
Wenn man high-gravity braut, rechnet der KBH ja die Menge Wasser aus, die man zumischen muss, um auf die Zielstammwürze zu kommen. Version 1.4.4.1 hat noch den Knopf "zumischen", der die neue Menge und Stammwürze dann weiter unten einträgt. In der Version aus dem Repo hier fehlt dieser Knopf, so dass man die Werte fürs Anstellen von Hand eingeben muss.

![zumischen](https://user-images.githubusercontent.com/134957/36365388-a36f16ac-1549-11e8-9737-76203fea5ef4.png)

**Comment by BourgeoisLab** [comment]
Ja das habe ich geändert. Das Program kann nicht wissen, wieviel Wasser man schlussendlich zugemischt hat und schon gar nicht die daraus resultierende Stammwürze. Der Button "Zumischen" ging einfach davon aus, dass die Stammwürze gleich der Zielstammwürze war. Das muss aber nicht sein.

Neu ist ein Feld "Wassermenge, um auf Sollstammwürze zu verdünnen". Beim Ändern des Feldes "Würzemenge beim Anstellen" wird das Feld aktualisiert, so dass es optimalerweise am Schluss bei 0.0 Liter steht.

**Comment by ivh** [comment]
Ah, jetzt versteh ich das,danke! Kleine "annoyance": Wenn man seine Anstellmenge und Stammwürze einträgtg und dann im nächsten Feld die Sepisemenge anpasst, springt die Menge zurück auf die nach dem Hopfenseien.
