### ISSUE TITLE
Crash when adding hops from template

### ISSUE THREAD

**Issue by ivh** [Gremmel/kleiner-brauhelfer#55]
I run the latest master via Qt-creator. When I just tried to add hops to the invetory ("aus Vorlage"), KBH crashed, see attached trace.

After restart, my list of hops templates to add from is empty.

[trace.txt](https://github.com/Gremmel/kleiner-brauhelfer/files/1851230/trace.txt)

**Comment by ivh** [comment]
It seems I clicked "Vorlage hinzufügen" to cause that crash, not "OK" on the dialogue "Auswahl Rohstoffvorlage". At least this way I can reproduce it.

"Liste wiederherstellen" worked as it should, by the way.

**Comment by BourgeoisLab** [comment]
Thanks for the report, much appreciated. I fixed it.
