### ISSUE TITLE
IBU calculation for high-gravity off?

### ISSUE THREAD

**Issue by ivh** [Gremmel/kleiner-brauhelfer#60]
When I change the high-gravity factor from 0 to e.g. 30% in KBH, all other numbers equal, it suggests decreasing hop additions.

It seems however that hop utilization decreases with boil gravity, meaning that hop additions should increase with HG-factor. According to Plamer's HowToBrew, the correction factor is 1.65*0.000125^(GB-1) with GB being the gravity at boil.

**Comment by BourgeoisLab** [comment]
I can't observe this issue. If I increase the HGF then the hops goes up too. Do you still have this issue?

We use a lookup table for the hops.

**Comment by ivh** [comment]
No, it seems I cannot reproduce it any more.

Thanks anyway!
