### ISSUE TITLE
1.4.5.0RC1 - Split Beer calculation inverted

### ISSUE THREAD

**Issue by freibadschwimmer** [Gremmel/kleiner-brauhelfer#62]
First of all, I love the new function to split beer and it comes just at the right time for me :-)
Thanks for this function!

I discovered, when splitting beer, the calculation is inverted:
For example, when selecting Beer A to be 40% and Beer B to be 60%, after the split Beer B remains with 40% and Beer A with 60%; so the split occurs inverted to the selection.

**Comment by BourgeoisLab** [comment]
fixed.
