### ISSUE TITLE
Ingredients drop down is initially empty (1.4.5.0 RC1)

### ISSUE THREAD

**Issue by LondonRain** [Gremmel/kleiner-brauhelfer#67]
See:
https://hobbybrauer.de/forum/viewtopic.php?p=279185#p279185
https://hobbybrauer.de/forum/viewtopic.php?p=279187#p279187

**Comment by BourgeoisLab** [comment]
This should be fixed in the meantime. Yesterday I fixed the bug with the empty "Brauanlage".
