### ISSUE TITLE
Wish: full text search in overview

### ISSUE THREAD

**Issue by scooterama** [Gremmel/kleiner-brauhelfer#75]
like in https://hobbybrauer.de/forum/viewtopic.php?f=3&t=161&p=270638#p270638
not only name-search, but 
filter/search all recipes with search term (ingredients, note, comment, term etc.). 
"w34" brings all/potencial recipes with yeast xy or comments with xy
"pils" brings all/potencial recipes with barley xy or comments with xy

**Comment by BourgeoisLab** [comment]
Text filter now looks also in ingredients and comment.
