### ISSUE TITLE
Feature Request: Import JSON data from www.maischemalzundmehr.de

### ISSUE THREAD

**Issue by realholgi** [Gremmel/kleiner-brauhelfer#8]
There is a new feature on http://www.maischemalzundmehr.de/ to export the receipes in JSON format(JSON button up right o each receipe page).

Please add a feature to import these receipes into KBH by using this data.

Example JSON: 
[rezept.json.txt](https://github.com/Gremmel/kleiner-brauhelfer/files/601923/rezept.json.txt)

**Comment by bitwave** [comment]
Maybe it is possible to do a simple in memory conversation from MMuM json to XSUD, reusing the XML parsing code.

**Comment by bitwave** [comment]
Partially solved by https://github.com/bitwave/json2xsud
