### ISSUE TITLE
Fehler beim Start von 1.4.4.3 (Windows)

### ISSUE THREAD

**Issue by apilz** [Gremmel/kleiner-brauhelfer#81]
Nach der Installation von https://github.com/Gremmel/kleiner-brauhelfer/releases/download/v1.4.4.3/kb_setup_v1_4_4_3.exe
Sehe ich beim Start nur folgenden Fehler:
![image](https://user-images.githubusercontent.com/6640244/48967751-c5ce9700-efe5-11e8-9b58-e99a5157f6e1.png)
Denke die sqlite-Datenbank im Installer ist nicht auf dem 1.4.4.3-Stand.

**Comment by BourgeoisLab** [comment]
Installiere und starte die version 1.4.4.2. Danach wieder 1.4.4.3 installieren.

Wie richtig bemerkt hat die 1.4.4.3 ein Problem mit der Erstinstallation. Wurde bereits für die nächste Version behoben.

**Comment by apilz** [comment]
Danke!
