### ISSUE TITLE
Zurücksetzen der Schnellsuche

### ISSUE THREAD

**Issue by LondonRain** [Gremmel/kleiner-brauhelfer#87]
Ab jetzt auf Deutsch, da @Gremmel das angeregt hatte. :)

![grafik](https://user-images.githubusercontent.com/33151586/50387734-019f6e00-0704-11e9-892e-c1afe03e0dce.png)

Ich vermisse da ein "x" rechts in der Textbox, um den Text zurück auf null zu setzen.

**Comment by Gremmel** [comment]
lach :) ...ich mag die "x"e neben den Suchfeldern eigentlich auch ;-)
