### ISSUE TITLE
Export recipes to JSON

### ISSUE THREAD

**Issue by Bavilo** [Gremmel/kleiner-brauhelfer#9]
Hello,

would it be possible to export a selected recipe to a standard JSON file as MMuM does it? I would love to read this JSON into my Android Brewing App. I decided against the use of JSON files from MMuM directly because their JSON files are sometimes incomplete. I also enter all the data from MMuM into the KBH anyway. So an export from KBH to JSON would be great!

Thanks
Michael

**Comment by bitwave** [comment]
Which brewing app do you use? I'm curious.

**Comment by Bavilo** [comment]
I wrote my own App and Brewing control. I explained some of it here:
https://hobbybrauer.de/forum/viewtopic.php?f=58&t=9937

I´m not really offering support anymore since most people just want to build and write their own control so there really is no point maintaining this project any further.

**Comment by bitwave** [comment]
Looks promising, but the Google Play link does not work :(

**Comment by Bavilo** [comment]
Yep, I have taken it offline.

**Comment by bitwave** [comment]
:(

**Comment by bitwave** [comment]
A nice Android App as companion to the brauhelfer would be awesome, in particular for small recipe adjustments or changes.

**Comment by BourgeoisLab** [comment]
Have a look here;)
http://github.com/BourgeoisLab/kleiner-brauhelfer-app

**Comment by bitwave** [comment]
Do you have binaries there?

**Comment by BourgeoisLab** [comment]
No. For what platform do you need? I can compile something later.

**Comment by bitwave** [comment]
Android APK?

**Comment by BourgeoisLab** [comment]
I managed to generate an APK (armeabi-v7a). If you are still interested I can send it to you.

**Comment by bitwave** [comment]
This would be awesome!

Frédéric Bourgeois <notifications@github.com> schrieb am So., 22. Okt.
2017, 15:54:

**Comment by BourgeoisLab** [comment]
Here you go. [kleiner-brauhelfer-app-v1.0.0-armeabi-v7a.apk.zip](https://github.com/Gremmel/kleiner-brauhelfer/files/1405061/kleiner-brauhelfer-app-v1.0.0-armeabi-v7a.apk.zip)

Note that it is for armeabi-v7a platform with Android 6.0 or higher. Tell me if you need a different platorm/version.

Also note that for dropbox synchronization you need to create a dropbox app (see http://www.dropbox.com/developers)
