### ISSUE TITLE
Vorschaufenster in Sudauswahl bricht nicht ordentlich um

### ISSUE THREAD

**Issue by LondonRain** [Gremmel/kleiner-brauhelfer#90]
Der Text in dem Vorschaufenster, rechts in der Sudauswahl, wird nicht ordentlich umgebrochen.

![grafik](https://user-images.githubusercontent.com/33151586/50546222-66872680-0c24-11e9-9cd4-f96c17c767b8.png)
![grafik](https://user-images.githubusercontent.com/33151586/50546226-730b7f00-0c24-11e9-9043-c3c4085d3129.png)

Edit: 1.4.45, Windows 7 64 bit

**Comment by BourgeoisLab** [comment]
fixed
