### ISSUE TITLE
Feldreihenfolge Reiter 'Rezept'

### ISSUE THREAD

**Issue by Roemergaertenbier** [Gremmel/kleiner-brauhelfer#93]
Hi,

ich mag den kbh und als Tastaturbenutzer schlage ich vor die Reihenfolge der Eingabefelder im Reiter 'Rezept' so anzuordnen, dass man nach der Eingabe des Sudnamens mittels [TAB]-Taste in das Nr-Feld gelangt. In meiner v1.4.4.5 gelangt man dort erst nach der Reiter-Auswahl Malz hin.

Ok, das ist nichts wichtiges, ist mir nur bei der Bedienung aufgefallen. Sonst TipTop!

Jan

**Comment by realholgi** [comment]
behoben.
